#pragma once

#include "CoreMinimal.h"
#include "KashmirGuardResolver.generated.h"


USTRUCT(BlueprintType)
struct KASHMIRUE_API FKashmirGuardInput
{
    GENERATED_BODY()

    /** Whether the attack was successfully blocked geometrically. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool bBlocked = false;

    /** Base guard damage generated by the attack. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float BaseGuardDamage = 0.0f;

    /**
     * Defensive multiplier.
     *
     * 1.0 = normal guard damage
     * 0.5 = takes half guard damage
     * 2.0 = takes double guard damage
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float GuardDamageMultiplier = 1.0f;

    /** Defender stamina available before guard resolution. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    float AvailableStamina = 0.0f;

    bool IsValid(
        FString& OutReason
    ) const;
};


USTRUCT(BlueprintType)
struct KASHMIRUE_API FKashmirGuardResult
{
    GENERATED_BODY()

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    bool bGuardProcessed = false;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    bool bGuardBroken = false;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    float RawGuardDamage = 0.0f;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    float FinalGuardDamage = 0.0f;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    float StaminaBefore = 0.0f;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    float StaminaAfter = 0.0f;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
    float AppliedStaminaDamage = 0.0f;
};


class KASHMIRUE_API FKashmirGuardResolver
{
public:

    bool Resolve(
        const FKashmirGuardInput& Input,
        FKashmirGuardResult& OutResult,
        FString& OutReason
    ) const;
};