#if WITH_DEV_AUTOMATION_TESTS
#include "Misc/AutomationTest.h"
#include "Runtime/KashmirActionRuntime.h"
namespace UE03 { static FGameplayTag T(const TCHAR* N) { return FGameplayTag::RequestGameplayTag(FName(N)); } static FKashmirResourcePool P(FGameplayTag T, float C) { FKashmirResourcePool X; X.ResourceTag=T; X.Current=C; X.Maximum=C; return X; } static FKashmirResourceCost C(FGameplayTag T, float A) { FKashmirResourceCost X; X.ResourceTag=T; X.Amount=A; return X; } static FKashmirActionDefinition A(FName I,float S,float Ac,float R,float Cost,bool Cancel=false) { FKashmirActionDefinition X; X.ActionId=I; X.StartupDuration=S; X.ActiveDuration=Ac; X.RecoveryDuration=R; X.bCancellable=Cancel; X.StartCosts.Add(C(T(TEXT("Resource.Stamina")),Cost)); return X; } }
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FKashmirResourceAtomicTest, "Kashmir.Foundation.Runtime.ResourceAtomic", EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)
bool FKashmirResourceAtomicTest::RunTest(const FString&) { using namespace UE03; auto Stamina=T(TEXT("Resource.Stamina")); auto Mana=T(TEXT("Resource.Mana")); FKashmirResourceRuntime R({P(Stamina,20),P(Mana,30)}); FKashmirResourcePaymentResult Q; TestTrue(TEXT("funded multi-resource payment succeeds"),R.Pay({C(Stamina,14),C(Mana,10)},Q)); TestTrue(TEXT("stamina spent"),FMath::IsNearlyEqual(R.GetCurrent(Stamina),6)); TestTrue(TEXT("mana spent"),FMath::IsNearlyEqual(R.GetCurrent(Mana),20)); TestFalse(TEXT("unfunded payment fails atomically"),R.Pay({C(Stamina,7),C(Mana,5)},Q)); TestTrue(TEXT("stamina preserved after failure"),FMath::IsNearlyEqual(R.GetCurrent(Stamina),6)); TestTrue(TEXT("mana preserved after failure"),FMath::IsNearlyEqual(R.GetCurrent(Mana),20)); return true; }
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FKashmirActionTimelineCancellationTest, "Kashmir.Foundation.Runtime.TimelineCancellation", EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)
bool FKashmirActionTimelineCancellationTest::RunTest(const FString&) { using namespace UE03; auto Stamina=T(TEXT("Resource.Stamina")); FKashmirResourceRuntime R({P(Stamina,40)}); auto Cut=A(TEXT("cut_down"),.2f,.24f,.26f,14,true); Cut.CancelWindows.Add(EKashmirActionPhase::Startup); auto Dodge=A(TEXT("dodge"),.1f,.1f,.3f,18); TMap<FName,FKashmirActionDefinition> D; D.Add(Cut.ActionId,Cut); D.Add(Dodge.ActionId,Dodge); FKashmirActionRuntime Runtime(D,{},R); FString Reason; FKashmirActionRequest CutRequest; CutRequest.ActionId=Cut.ActionId; FKashmirActionRequest DodgeRequest; DodgeRequest.ActionId=Dodge.ActionId; TestTrue(TEXT("cut starts"),Runtime.Start(CutRequest,Reason)); TestTrue(TEXT("startup advances"),Runtime.Advance(.1f,Reason)); TestEqual(TEXT("startup observable"),Runtime.GetState().Phase,EKashmirActionPhase::Startup); TestTrue(TEXT("startup cancellation starts replacement"),Runtime.TryCancel(DodgeRequest,Reason)); TestTrue(TEXT("costs remain committed"),FMath::IsNearlyEqual(R.GetCurrent(Stamina),8)); TestEqual(TEXT("dodge active"),Runtime.GetState().ActionId,Dodge.ActionId); return true; }
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FKashmirActionTransitionTest, "Kashmir.Foundation.Runtime.TaggedTransitions", EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)
bool FKashmirActionTransitionTest::RunTest(const FString&) { using namespace UE03; FKashmirResourceRuntime R({P(T(TEXT("Resource.Stamina")),30)}); auto Cut=A(TEXT("cut_down"),.2f,.24f,.26f,1); auto Lunge=A(TEXT("lunge"),.1f,.2f,.2f,1); TMap<FName,FKashmirActionDefinition> D; D.Add(Cut.ActionId,Cut); D.Add(Lunge.ActionId,Lunge); FKashmirTransitionRule Rule; Rule.FromActionId=Cut.ActionId; Rule.ToActionId=Lunge.ActionId; Rule.MinElapsed=.1f; Rule.MaxElapsed=.2f; Rule.RequiredTags.AddTag(T(TEXT("Action.Transition"))); Rule.BlockedTags.AddTag(T(TEXT("State.Disabled"))); FKashmirActionRuntime Runtime(D,{Rule},R); FString Reason; FKashmirActionRequest Request; Request.ActionId=Cut.ActionId; TestTrue(TEXT("source starts"),Runtime.Start(Request,Reason)); Runtime.Advance(.1f,Reason); FGameplayTagContainer Context; Context.AddTag(T(TEXT("Action.Transition"))); TestTrue(TEXT("tagged window offers transition"),Runtime.GetTransitionOptions(Context).Contains(Lunge.ActionId)); Context.AddTag(T(TEXT("State.Disabled"))); TestFalse(TEXT("blocked tag suppresses transition"),Runtime.GetTransitionOptions(Context).Contains(Lunge.ActionId)); Context.RemoveTag(T(TEXT("State.Disabled"))); FKashmirActionRequest Next; Next.ActionId=Lunge.ActionId; TestTrue(TEXT("rule permits transition"),Runtime.TransitionTo(Next,Context,Reason)); TestEqual(TEXT("target becomes active"),Runtime.GetState().ActionId,Lunge.ActionId); return true; }
#endif
