param([string]$UnrealRoot = 'C:\Program Files\Epic Games\UE_5.8',[string]$KashmirActRoot = 'C:\Projetos\KashmirAct',[switch]$SkipBuild)
$ErrorActionPreference = 'Stop'
$projectRoot=(Resolve-Path (Join-Path $PSScriptRoot '../..')).Path; $projectFile=Join-Path $projectRoot 'KashmirUE.uproject'; $outputDir=Join-Path $projectRoot 'Saved/Validation'; $buildScript=Join-Path $UnrealRoot 'Engine/Build/BatchFiles/Build.bat'; $editorCmd=Join-Path $UnrealRoot 'Engine/Binaries/Win64/UnrealEditor-Cmd.exe'; $exportScript=Join-Path $KashmirActRoot 'tools/migration/export_unreal_ue02_artifacts.py'
New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
function Invoke-Gate([string]$Name,[string[]]$Arguments) { $log=Join-Path $outputDir "$Name.log"; $ErrorActionPreference='Continue'; & $editorCmd $projectFile @Arguments *> $log; $exitCode=$LASTEXITCODE; $ErrorActionPreference='Stop'; if($exitCode -ne 0){throw "$Name failed with exit code $exitCode. Inspect $log"}; Write-Output "$Name PASS" }
if(!(Test-Path -LiteralPath $projectFile)){throw 'KashmirUE.uproject is missing.'}; if(!(Test-Path -LiteralPath $buildScript)){throw "Build script missing: $buildScript"}; if(!(Test-Path -LiteralPath $editorCmd)){throw "UnrealEditor-Cmd missing: $editorCmd"}; if(!(Test-Path -LiteralPath $exportScript)){throw 'UE artifact export script is missing.'}
& python $exportScript --unreal-root $projectRoot; if($LASTEXITCODE -ne 0){throw 'Artifact export failed.'}; Write-Output 'artifact_export PASS'
$manifest=Get-Content -Raw -LiteralPath (Join-Path $projectRoot 'Docs/ASSET_MANIFEST_v1.json')|ConvertFrom-Json; $fixtures=Get-Content -Raw -LiteralPath (Join-Path $projectRoot 'Content/KashmirAct/Data/GoldenFixtures/KashmirGoldenFixtures_v1.json')|ConvertFrom-Json
if($manifest.manifest_schema_version -ne '1.0.0' -or $manifest.assets.Count -lt 1){throw 'Asset manifest is invalid.'}; if($fixtures.schema_version -ne '1.0.0' -or $fixtures.fixtures.Count -ne 14){throw 'Golden fixture document is invalid.'}; Write-Output 'artifact_schema PASS'
if(!$SkipBuild){& $buildScript KashmirUEEditor Win64 Development "-Project=$projectFile" -WaitMutex -NoHotReload; if($LASTEXITCODE -ne 0){throw 'KashmirUEEditor build failed.'}; Write-Output 'build PASS'}
Invoke-Gate 'data_validation' @('-run=DataValidation','-unattended','-nop4','-NullRHI'); Invoke-Gate 'automation' @('-ExecCmds=Automation RunTests Kashmir.Foundation; Quit','-TestExit=Automation Test Queue Empty','-unattended','-nop4','-NullRHI')
& git diff --check; if($LASTEXITCODE -ne 0){throw 'git diff --check failed.'}; & git status --short; if($LASTEXITCODE -ne 0){throw 'git status failed.'}; Write-Output 'KASHMIR_UE0_3_CONSOLIDATED_PASS'
