#include "Runtime/KashmirActionRuntime.h"

bool FKashmirResourcePool::IsValid(FString& OutReason) const { if (!ResourceTag.IsValid()) { OutReason = TEXT("resource tag is required"); return false; } if (!FMath::IsFinite(Current) || !FMath::IsFinite(Maximum) || Current < 0.0f || Maximum < 0.0f || Current > Maximum) { OutReason = TEXT("resource pool values are invalid"); return false; } return true; }
bool FKashmirResourceCost::IsValid(FString& OutReason) const { if (!ResourceTag.IsValid()) { OutReason = TEXT("resource cost tag is required"); return false; } if (!FMath::IsFinite(Amount) || Amount < 0.0f) { OutReason = TEXT("resource cost cannot be negative"); return false; } return true; }
FKashmirResourceRuntime::FKashmirResourceRuntime(const TArray<FKashmirResourcePool>& InPools) { for (const FKashmirResourcePool& Pool : InPools) { FString Reason; if (Pool.IsValid(Reason) && !Pools.Contains(Pool.ResourceTag)) { Pools.Add(Pool.ResourceTag, Pool); } } }
bool FKashmirResourceRuntime::CanPay(const TArray<FKashmirResourceCost>& Costs, FKashmirResourcePaymentResult& OutResult) const { OutResult = {}; TMap<FGameplayTag, float> Totals; for (const auto& Cost : Costs) { FString Reason; if (!Cost.IsValid(Reason)) { OutResult.Errors.Add(Reason); } else { Totals.FindOrAdd(Cost.ResourceTag) += Cost.Amount; } } for (const auto& Pair : Totals) { const FKashmirResourcePool* Pool = Pools.Find(Pair.Key); if (!Pool) { OutResult.Errors.Add(FString::Printf(TEXT("unknown resource: %s"), *Pair.Key.ToString())); } else if (Pool->Current + KINDA_SMALL_NUMBER < Pair.Value) { OutResult.Errors.Add(FString::Printf(TEXT("insufficient resource: %s"), *Pair.Key.ToString())); } } OutResult.bPaid = OutResult.Errors.IsEmpty(); return OutResult.bPaid; }
bool FKashmirResourceRuntime::Pay(const TArray<FKashmirResourceCost>& Costs, FKashmirResourcePaymentResult& OutResult) { if (!CanPay(Costs, OutResult)) { return false; } TMap<FGameplayTag, float> Totals; for (const auto& Cost : Costs) { Totals.FindOrAdd(Cost.ResourceTag) += Cost.Amount; } for (const auto& Pair : Totals) { FKashmirResourcePool& Pool = Pools.FindChecked(Pair.Key); FKashmirResourceChange Change; Change.ResourceTag = Pair.Key; Change.Before = Pool.Current; Pool.Current -= Pair.Value; Change.After = Pool.Current; OutResult.Changes.Add(Change); } OutResult.bPaid = true; return true; }
bool FKashmirResourceRuntime::Regenerate(const FGameplayTag& Tag, float Delta, float Rate, FString& OutReason) { if (!FMath::IsFinite(Delta) || !FMath::IsFinite(Rate) || Delta < 0.0f || Rate < 0.0f) { OutReason = TEXT("regeneration values are invalid"); return false; } FKashmirResourcePool* Pool = Pools.Find(Tag); if (!Pool) { OutReason = FString::Printf(TEXT("unknown resource: %s"), *Tag.ToString()); return false; } Pool->Current = FMath::Min(Pool->Maximum, Pool->Current + Delta * Rate); return true; }
float FKashmirResourceRuntime::GetCurrent(const FGameplayTag& Tag) const { const FKashmirResourcePool* Pool = Pools.Find(Tag); return Pool ? Pool->Current : 0.0f; }

float FKashmirActionDefinition::GetTotalDuration() const { return StartupDuration + ActiveDuration + RecoveryDuration; }
bool FKashmirActionDefinition::IsValid(FString& OutReason) const { if (ActionId.IsNone()) { OutReason = TEXT("action id is required"); return false; } if (!FMath::IsFinite(StartupDuration) || !FMath::IsFinite(ActiveDuration) || !FMath::IsFinite(RecoveryDuration) || StartupDuration < 0.0f || ActiveDuration < 0.0f || RecoveryDuration < 0.0f || GetTotalDuration() <= 0.0f) { OutReason = TEXT("action durations are invalid"); return false; } for (const auto& Cost : StartCosts) { if (!Cost.IsValid(OutReason)) { return false; } } return true; }
bool FKashmirTransitionRule::IsValid(FString& OutReason) const { if (FromActionId.IsNone() || ToActionId.IsNone()) { OutReason = TEXT("transition action ids are required"); return false; } if (!FMath::IsFinite(MinElapsed) || !FMath::IsFinite(MaxElapsed) || MinElapsed < 0.0f || (MaxElapsed >= 0.0f && MaxElapsed < MinElapsed)) { OutReason = TEXT("transition window is invalid"); return false; } return true; }

FKashmirActionRuntime::FKashmirActionRuntime(const TMap<FName, FKashmirActionDefinition>& InDefinitions, const TArray<FKashmirTransitionRule>& InTransitions, FKashmirResourceRuntime& InResources) : Definitions(InDefinitions), Transitions(InTransitions), Resources(InResources) {}
bool FKashmirActionRuntime::Validate(const FKashmirActionRequest& Request, const FKashmirActionDefinition*& OutDefinition, FString& OutReason) const { if (!Request.IsValid(OutReason)) return false; OutDefinition = Definitions.Find(Request.ActionId); if (!OutDefinition) { OutReason = FString::Printf(TEXT("unknown action: %s"), *Request.ActionId.ToString()); return false; } return OutDefinition->IsValid(OutReason); }
void FKashmirActionRuntime::Begin(const FKashmirActionDefinition& Definition) { ActiveActionId = Definition.ActionId; Elapsed = 0.0f; bActive = true; bInterrupted = false; bCompleted = false; AppendEvent(EKashmirActionEventType::Started, ActiveActionId); }
bool FKashmirActionRuntime::PayAndBegin(const FKashmirActionRequest&, const FKashmirActionDefinition& Definition, FString& OutReason) { FKashmirResourcePaymentResult Payment; if (!Resources.Pay(Definition.StartCosts, Payment)) { OutReason = FString::Join(Payment.Errors, TEXT("; ")); return false; } Begin(Definition); return true; }
bool FKashmirActionRuntime::Start(const FKashmirActionRequest& Request, FString& OutReason) { if (bActive) { OutReason = TEXT("an action is already active"); return false; } const FKashmirActionDefinition* Definition = nullptr; return Validate(Request, Definition, OutReason) && PayAndBegin(Request, *Definition, OutReason); }
EKashmirActionPhase FKashmirActionRuntime::ResolvePhase() const { if (bInterrupted) return EKashmirActionPhase::Interrupted; if (bCompleted) return EKashmirActionPhase::Complete; if (!bActive) return EKashmirActionPhase::Inactive; const FKashmirActionDefinition* Definition = Definitions.Find(ActiveActionId); if (!Definition) return EKashmirActionPhase::Inactive; if (Elapsed < Definition->StartupDuration) return EKashmirActionPhase::Startup; if (Elapsed < Definition->StartupDuration + Definition->ActiveDuration) return EKashmirActionPhase::Active; return EKashmirActionPhase::Recovery; }
bool FKashmirActionRuntime::Advance(float DeltaSeconds, FString& OutReason) { if (!FMath::IsFinite(DeltaSeconds) || DeltaSeconds < 0.0f) { OutReason = TEXT("delta seconds cannot be negative"); return false; } if (!bActive) return true; const FKashmirActionDefinition* Definition = Definitions.Find(ActiveActionId); if (!Definition) { OutReason = TEXT("active action definition is missing"); return false; } Elapsed = FMath::Min(Elapsed + DeltaSeconds, Definition->GetTotalDuration()); if (Elapsed >= Definition->GetTotalDuration()) { bActive = false; bCompleted = true; AppendEvent(EKashmirActionEventType::Completed, ActiveActionId); } return true; }
bool FKashmirActionRuntime::TryCancel(const FKashmirActionRequest& NextRequest, FString& OutReason) { const FKashmirActionDefinition* Current = Definitions.Find(ActiveActionId); if (!bActive || !Current || !Current->bCancellable || !Current->CancelWindows.Contains(ResolvePhase())) { OutReason = TEXT("action cannot be cancelled in current phase"); return false; } const FKashmirActionDefinition* Next = nullptr; if (!Validate(NextRequest, Next, OutReason)) return false; FKashmirResourcePaymentResult Payment; if (!Resources.Pay(Next->StartCosts, Payment)) { OutReason = FString::Join(Payment.Errors, TEXT("; ")); return false; } bActive = false; bInterrupted = true; AppendEvent(EKashmirActionEventType::Interrupted, ActiveActionId); Begin(*Next); return true; }
TArray<FName> FKashmirActionRuntime::GetTransitionOptions(const FGameplayTagContainer& Context) const { struct FCandidate { FName Id; int32 Priority; }; TArray<FCandidate> Candidates; if (!bActive) return {}; for (const auto& Rule : Transitions) { FString Reason; if (!Rule.IsValid(Reason) || Rule.FromActionId != ActiveActionId || Elapsed + KINDA_SMALL_NUMBER < Rule.MinElapsed || (Rule.MaxElapsed >= 0.0f && Elapsed - KINDA_SMALL_NUMBER > Rule.MaxElapsed) || !Context.HasAll(Rule.RequiredTags) || Context.HasAny(Rule.BlockedTags)) continue; Candidates.Add({Rule.ToActionId, Rule.Priority}); } Candidates.Sort([](const FCandidate& A, const FCandidate& B) { return A.Priority != B.Priority ? A.Priority > B.Priority : A.Id.LexicalLess(B.Id); }); TArray<FName> Result; for (const auto& Candidate : Candidates) Result.Add(Candidate.Id); return Result; }
bool FKashmirActionRuntime::TransitionTo(const FKashmirActionRequest& NextRequest, const FGameplayTagContainer& Context, FString& OutReason) { if (!GetTransitionOptions(Context).Contains(NextRequest.ActionId)) { OutReason = TEXT("transition is not available"); return false; } const FKashmirActionDefinition* Next = nullptr; if (!Validate(NextRequest, Next, OutReason)) return false; FKashmirResourcePaymentResult Payment; if (!Resources.Pay(Next->StartCosts, Payment)) { OutReason = FString::Join(Payment.Errors, TEXT("; ")); return false; } AppendEvent(EKashmirActionEventType::Transitioned, ActiveActionId); Begin(*Next); return true; }
FKashmirActionRuntimeState FKashmirActionRuntime::GetState() const { FKashmirActionRuntimeState State; State.ActionId = ActiveActionId; State.Phase = ResolvePhase(); State.Elapsed = Elapsed; State.bActive = bActive; return State; }
void FKashmirActionRuntime::AppendEvent(EKashmirActionEventType Type, FName ActionId) { FKashmirActionEvent Event; Event.EventId = FName(*FString::Printf(TEXT("action_%06d"), NextEventSequence++)); Event.Type = Type; Event.ActionId = ActionId; Event.Timestamp = Elapsed; Events.Add(Event); }
TArray<FKashmirActionEvent> FKashmirActionRuntime::DrainEvents() { TArray<FKashmirActionEvent> Result = MoveTemp(Events); Events.Reset(); return Result; }
